server:
  port: 3344
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:github-of-lyj/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

